services:
  keycloak:
    image: keycloak/keycloak:21.1.0
    container_name: keycloak-v21
    ports:
      - 4000:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_HTTP_RELATIVE_PATH: /auth
      # DB設定
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://keycloak-mysql:3306/keycloak
      KC_DB_USERNAME: db-user
      KC_DB_PASSWORD: password
    command: start-dev

networks:
  default:
    name: keycloak-network
    external: true