# KeycloakサーバーのベースURL
@host = http://localhost:4000

# レルム名
@realm = your-realm-name

# クライアントID
@client = your-client-id

# アクセストークン
@accessToken = your-access-token after Step1

# state
@state = your-state-value

# nonce
@nonce = your-nonce-value

### =============================================
### Step1: Request Token (execute on browser)
### =============================================
GET {{host}}/auth/realms/{{realm}}/protocol/openid-connect/auth
?client_id={{client}}
&response_type=id_token token
&scope=openid
&redirect_uri=http://localhost:3000/callback
&state=abcdefg
&nonce=1234567890

### =============================================
### Step2: Request User Info
### =============================================
# @name userInfoRequest
GET {{host}}/auth/realms/{{realm}}/protocol/openid-connect/userinfo
Authorization: Bearer {{accessToken}}