version: "3"

services:
  mysql:
    image: mysql:8.0.33
    container_name: keycloak-mysql
    volumes:
      - keycloak-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: keycloak
      MYSQL_USER: db-user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

volumes:
  keycloak-mysql-data:
    external: true

networks:
  default:
    name: keycloak-network
    external: true